build:
	git submodule update --init --recursive

	scons platform=macos arch=universal target=template_debug -j4
#	scons platform=macos arch=universal target=template_release -j4

# 	scons platform=linux arch=arm64 target=template_debug -j4
# 	scons platform=linux arch=arm64 target=template_release -j4
# 	scons platform=linux arch=x86_64 target=template_debug -j4
# 	scons platform=linux arch=x86_64 target=template_release -j4

# 	scons platform=windows arch=x86_64 target=template_debug -j4
# 	scons platform=windows arch=x86_64 target=template_release -j4
